/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import model.*;
import service.*;

import java.util.List;
import java.util.ArrayList;
import java.math.BigDecimal;

public class Inicio extends javax.swing.JFrame {
    
    private Usuario usuarioLogado;
    private CarrinhoModel carrinhoDoUsuario;

    public Inicio(Usuario usuarioLogado) {
        initComponents();

        this.usuarioLogado = usuarioLogado;
        
        CarrinhoService carrinoService = new CarrinhoService();
        
        //busca o carrinho e deixa-o na memória
        this.carrinhoDoUsuario = carrinoService.BuscarCarrinho(usuarioLogado);
        
        //Se houver itens no carrinho, exibe o botão de carrinho
        List<Jogo> jogos = carrinoService.BuscarJogosCarrinho(usuarioLogado);
        System.out.println("tamanho: "+jogos.size());
        btnCarrinho.setVisible(false);
        if(jogos != null && jogos.size() != 0)
            btnCarrinho.setVisible(true);
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnJogos = new javax.swing.JButton();
        btnTesteAddJogoCarrinho = new javax.swing.JButton();
        btnCarrinho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Tela Inicial");

        btnJogos.setText("Jogos");
        btnJogos.addActionListener(this::btnJogosActionPerformed);

        btnTesteAddJogoCarrinho.setText("adicionar minecraft no carrinho");
        btnTesteAddJogoCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTesteAddJogoCarrinhoMouseClicked(evt);
            }
        });

        btnCarrinho.setText("carrinho");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCarrinho)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(166, 166, 166)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(btnJogos)
                            .addGap(34, 34, 34)
                            .addComponent(btnTesteAddJogoCarrinho))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnCarrinho)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJogos)
                    .addComponent(btnTesteAddJogoCarrinho))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogosActionPerformed
        if (usuarioLogado != null) {

            this.dispose();

            new TelaJogos(usuarioLogado).setVisible(true);
        }
    }//GEN-LAST:event_btnJogosActionPerformed

    private void btnTesteAddJogoCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTesteAddJogoCarrinhoMouseClicked
        this.dispose();
        
        List<Jogo> jogos = new ArrayList<Jogo>();
        
        //teste de carrinho. Quando o usuário adicionar um jogo no carrinho
        //deve chamar o método CarrinhoService.AdicionarJogoCarrinho passando o usuario e o jogo selecionado
        //criei um jogo hardcoded aqui só pra teste, se vira ai caique
        CarrinhoService service = new CarrinhoService();
        Jogo minecraft = new Jogo("Minecraft", "minecraft Java 21.2", new BigDecimal(99.9));
        minecraft.setId(1);
        service.AdicionarJogoCarrinho(usuarioLogado, minecraft);

        jogos = service.BuscarJogosCarrinho(usuarioLogado);

        new Carrinho(jogos, carrinhoDoUsuario).setVisible(true);
    }//GEN-LAST:event_btnTesteAddJogoCarrinhoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JButton btnJogos;
    private javax.swing.JButton btnTesteAddJogoCarrinho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
